cmake_minimum_required(VERSION 4.1)
project(LPC)

set(CMAKE_CXX_STANDARD 20)

add_executable(LPC twosum.cpp
        "ada and queue.cpp"
        "teams forming.cpp"
        "Generalized Matrioshkas.cpp"
        "subarray sums 1.cpp"
        "Eliminating Ballons.cpp"
        "towers.cpp"
        "New year and hurry.cpp"
        "Binary search.cpp"
        "coins and triangle.cpp"
        "The Kth Time Query.cpp"
        "Eko.cpp"
        "corona virus.cpp"
        "Panoramix's Prediction.cpp"
        "A problem of Backtracking.cpp"
        "Chessboard and Queens.cpp"
        "Stone Pile.cpp"
        "Making Jumps.cpp"
        "Water Buying .cpp"
        "Apartments.cpp"
        "I AM VERY BUSY.cpp"
        "Stalin Sort.cpp"
        "Running Median Again.cpp"
        "Frog 1.cpp"
        "Longest Regular Bracket Sequence.cpp"
        "Hit the Lottery.cpp"
        "Coin Combinations I.cpp"
        "Book Shop.cpp"
        "Cut Ribbon.cpp"
        "LCS.cpp"
        Labyrinth.cpp
        "Building Roads.cpp"
        "Message Route.cpp"
        "Building Teams.cpp"
        "Round Trip.cpp"
        Monsters.cpp
        Friends.cpp
        "Galactic Bonding.cpp"
        "Is it a tree.cpp"
        Cthulhu.cpp
        Party.cpp
        "Tree Diameter.cpp"
        k-tree.cpp
        Journey.cpp
        "Shortest Routes I.cpp"
        "Shortest Routes II.cpp"
        Dijkstra.cpp
        Ford-Bellman.cpp
        "High Score.cpp"
        "Flight Discount.cpp"
        "Hongcow Builds A Nation.cpp"
        "Road Reparation.cpp"
        "Road Construction.cpp"
        Hierarchy.cpp
        "Help the old King.cpp"
        Modems.cpp)
